# agent.py — ADK Agent Template
#
# INSTRUCTIONS:
# 1. Replace each tool stub with your actual logic
# 2. Update root_agent's name, instruction, and tools list
# 3. Add your API key to .env: GOOGLE_API_KEY="your-key-here"
# 4. Run from parent folder: adk web
#
# MODEL SELECTION GUIDE:
#   gemini-2.5-flash — tool-calling, routing, data retrieval, most agents
#   gemini-2.5-pro   — code generation, complex reasoning, long context,
#                      synthesizing outputs from multiple sub-agents
#
# Generated by adk-builder skill for Gemini CLI

# ── Required: load .env before any ADK imports ────────────────────────────────
# Without this, adk web cannot read GOOGLE_API_KEY and your agent won't appear.
from dotenv import load_dotenv
load_dotenv()

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# OPTION A — Single Agent (simplest; use when one agent can do everything)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

from google.adk.agents import LlmAgent


# ── Tool 1 ────────────────────────────────────────────────────────────────────

def tool_one(param: str) -> dict:
    """One-line description of what this tool does.

    Args:
        param: Description of this parameter.

    Returns:
        A dictionary with status and the result.
    """
    try:
        result = f"Processed: {param}"
        return {"status": "success", "result": result}
    except Exception as e:
        return {"status": "error", "message": str(e)}


# ── Tool 2 ────────────────────────────────────────────────────────────────────

def tool_two(value_a: float, value_b: float) -> dict:
    """One-line description of what this tool does.

    Args:
        value_a: Description of first parameter.
        value_b: Description of second parameter.

    Returns:
        A dictionary with status and the computed result.
    """
    try:
        result = value_a + value_b
        return {"status": "success", "result": result}
    except Exception as e:
        return {"status": "error", "message": str(e)}


# ── Tool 3 ────────────────────────────────────────────────────────────────────

def tool_three() -> dict:
    """One-line description of what this tool does (no parameters needed).

    Returns:
        A dictionary with status and the result.
    """
    try:
        return {"status": "success", "result": "placeholder"}
    except Exception as e:
        return {"status": "error", "message": str(e)}


# ── Single Agent ──────────────────────────────────────────────────────────────
#
# Choose model:
#   gemini-2.5-flash — if this agent calls tools and handles clear user requests
#   gemini-2.5-pro   — if this agent generates code or reasons over complex tasks

root_agent = LlmAgent(
    name="my_agent",                    # ← change this
    model="gemini-2.5-flash",           # ← see model selection guide above
    instruction="""
        You are a [describe persona here]. You help users with [describe purpose].

        You have access to these tools:
        - tool_one: use when the user asks about [X]
        - tool_two: use when the user needs [Y]
        - tool_three: use when the user wants [Z]

        Always use the appropriate tool rather than guessing.
    """,
    tools=[tool_one, tool_two, tool_three],
)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# OPTION B — Coordinator + Specialists (use when agent has multiple domains)
#
# Uncomment this block and comment out OPTION A's root_agent to use it.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# from google.adk.agents import LlmAgent
# from google.adk.tools.agent_tool import AgentTool
#
#
# # ── Specialist A — give it the model that fits its specific job ───────────────
#
# def specialist_a_tool(param: str) -> dict:
#     """One-line description.
#
#     Args:
#         param: Description.
#     Returns:
#         Dict with status and result.
#     """
#     try:
#         return {"status": "success", "result": f"Specialist A processed: {param}"}
#     except Exception as e:
#         return {"status": "error", "message": str(e)}
#
# specialist_a = LlmAgent(
#     name="specialist_a",
#     model="gemini-2.5-pro",    # ← use pro if this specialist does complex reasoning
#     instruction="""
#         You are a [specialist A persona]. Handle [domain A] requests precisely.
#         - specialist_a_tool: use when [condition].
#         Always use the appropriate tool rather than guessing.
#     """,
#     tools=[specialist_a_tool],
# )
#
#
# # ── Specialist B ──────────────────────────────────────────────────────────────
#
# def specialist_b_tool(query: str) -> dict:
#     """One-line description.
#
#     Args:
#         query: Description.
#     Returns:
#         Dict with status and result.
#     """
#     try:
#         return {"status": "success", "result": f"Specialist B answered: {query}"}
#     except Exception as e:
#         return {"status": "error", "message": str(e)}
#
# specialist_b = LlmAgent(
#     name="specialist_b",
#     model="gemini-2.5-flash",  # ← use flash if this specialist does simple retrieval
#     instruction="""
#         You are a [specialist B persona]. Handle [domain B] requests efficiently.
#         - specialist_b_tool: use when [condition].
#         Always use the appropriate tool rather than guessing.
#     """,
#     tools=[specialist_b_tool],
# )
#
#
# # ── Coordinator ───────────────────────────────────────────────────────────────
# # Routes to the right specialist via AgentTool.
# # Use flash for simple routing; upgrade to pro if synthesis is complex.
#
# root_agent = LlmAgent(
#     name="coordinator",
#     model="gemini-2.5-flash",  # ← upgrade to pro if synthesizing complex outputs
#     instruction="""
#         You are a smart coordinator. Delegate every request to the right specialist:
#         - specialist_a: for [domain A] tasks
#         - specialist_b: for [domain B] tasks
#
#         Do not answer directly — always delegate to the right specialist.
#         Combine specialist outputs into a clear response for the user.
#     """,
#     tools=[
#         AgentTool(agent=specialist_a),
#         AgentTool(agent=specialist_b),
#     ],
# )
